### PR TITLE
Setup proper packages for luatex

### PR DESCRIPTION
**Pull request by maxnoe**
* fontspec instead of inputenc / fontenc
* additionally unicode-math
* use Fira Sans / Fira Math
* Add math and unit packages
* 16 by 10 aspect ratio (matches projectors in lecture halls @ Dortmund)

### CODE REVIEW

**Review by hmoldenhauer — CHANGES_REQUESTED** [review]
Metropolis is included by default in recent latex releases? So the ../style/* files can be deleted?

**Comment by maxnoe** [comment]
Yes it is, but this has nothing to do with the contents of this PR, does it?

https://ctan.org/pkg/beamertheme-metropolis

**Comment by maxnoe** [comment]
Ah, right. I removed the relative path without chaning TEXINPUTS in the Makefile. Forgot to commit that

**Review by hmoldenhauer — APPROVED** [review]
top

**Pull request merged**
